#5: Provided an optional token input to provide a custom token for the action to use

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,6 +12,10 @@ inputs:
     description: Name of the changelog file (case-sensitive)
     required: false
     default: CHANGELOG.md
+  token:
+    description: Authentication token used to get PR information
+    required: true
+    default: "${{ github.token }}"
 runs:
   using: "composite"
   steps:
@@ -37,11 +41,15 @@ runs:
     shell: bash
     run: |
       if [ "${{ steps.pr_excused_check.outputs.pr_excused }}" != true ]; then
+        if ! curl --silent --fail --user "$OWNER":"$GITHUB_TOKEN" "$PR_API_URL" >/dev/null; then
+          echo "Could not fetch info about the current PR. Perhaps an invalid token was provided?" >&2
+          exit 1
+        fi
         $GITHUB_ACTION_PATH/verify_changelog_updated.sh
       fi
     env:
       PR_API_URL: ${{ github.event.pull_request._links.self.href }}
-      GITHUB_TOKEN: ${{ github.token }}
+      GITHUB_TOKEN: ${{ inputs.token }}
       OWNER: ${{ github.repository_owner }}
       EXCUSED_LABEL: ${{ inputs.excused_label }}
       CHANGELOG_FILENAME: ${{ inputs.changelog_filename }}
